# Generated by Django 3.2.2 on 2021-05-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0002_auto_20210510_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='pub_date',
            field=models.DateTimeField(),
        ),
    ]
