# Generated by Django 3.2.2 on 2021-05-11 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0004_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
